image: node:8

build:
  stage: build
  script:
  # Build
  - npm install
  - npm run gulp sass
  - rm -r public/fakeAPI
  - npm run build

  # Upload
  - tar -czvf pihole-web.tar.gz -C build .
  - wget https://ftl.pi-hole.net:8080/FTL-client
  - chmod +x ./FTL-client
  - ./FTL-client "$CI_COMMIT_REF_NAME" pihole-web.tar.gz "$FTL_SECRET"
  - rm ./FTL-client
  cache:
    key: branch:$CI_COMMIT_REF_SLUG
    paths:
    - node_modules/
  artifacts:
    paths:
    - pihole-web.tar.gz

deploy:
  stage: deploy
  variables:
    PUBLIC_URL: "/"
  script:
  # Build with fake data
  - npm install
  - npm run gulp sass
  - rm public/fakeAPI/.gitignore # Make sure that the fakeAPI data is deployed
  - npm run build-fake
  - echo "web.pi-hole.io" > build/CNAME

  # Deploy to GitHub Pages
  - git clone --depth 1 -b fake-deploy https://Mcat12:$GITHUB_ACCESS_TOKEN@github.com/pi-hole/web.git deploy
  - rm -rf deploy/!(.|..|.git)
  - cp build/* deploy/
  - cd deploy
  - git config user.email "4417660+Mcat12@users.noreply.github.com"
  - git config user.name "Mcat12"
  - git commit -am "(Fake) Deploy pi-hole/web to web.pi-hole.io"
  - git push
  cache:
    key: deploy
    paths:
    - node_modules/
  only:
  - gitlab-ci-deploy-test
  when: manual