language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
env:
  global:
    - PUBLIC_URL=/
script:
  - npm run gulp sass
  - rm public/fakeAPI/.gitignore # Make sure that the fakeAPI data is deployed
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then
      npm run build-fake;
      echo "web.pi-hole.io" > build/CNAME;
    else
      npm run build;
    fi'
  - tar -czvf pihole-web.tar.gz -C build .
  - wget https://ftl.pi-hole.net:8080/FTL-client
  - chmod +x ./FTL-client
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./FTL-client "${TRAVIS_BRANCH}" pihole-web.tar.gz "${TRAVIS_SECRET}"; fi'
  - rm ./FTL-client

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
